### ISSUE TITLE
Bug no setup

### ISSUE THREAD

**Issue by Daniel-Pinheiro** [fabiommendes/FGAme#5]
Quando se usa o comando 'setup.py build', dá erro acusando que 'src\FGAme\objects' não existe.

**Comment by fabiommendes** [comment]
Oi Daniel,

Apague o item 'FGAme.objects' da lista de packages dentro do arquivo
setup.py. Eu corrigi isto na versão mais nova, mas ainda não dei push
porque vai quebrar muita coisa.

Abraço,
Fábio

2015-06-26 16:47 GMT-03:00 danielborges36 notifications@github.com:
